Docker 2
Otus-DevOps-2021-02/mzabolotnov_microservices pull request #2
Opened 2021-05-11 07:14 UTC by mzabolotnov

2021-05-12 08:02 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз, оставил небольшой комментарий к файлам, к сожалению тесты красные, скорее всего это связано с тем что сервис ui не доступен, так же нужно добавить описание к пр. ДЗ возвращаю на доработку. 
![image](https://user-images.githubusercontent.com/34331259/117940164-772a2a00-b311-11eb-986e-3420c429283c.png)

2021-05-12 08:02 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Лушче пробовать собирать на 16.04 версии

2021-05-13 07:56 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к Dockerfile. ДЗ возвращаю на доработку.

2021-05-13 07:56 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +RUN cd /reddit && rm Gemfile.lock && bundle install
Не удаляйте Gemfile.lock, поправьте Dockerfile и попробуйте собрать образ снова =)

2021-05-15 09:24 UTC, mrgreyves requested changes
![image](https://user-images.githubusercontent.com/34331259/118355406-88c13b00-b578-11eb-9de5-c268cd5cc55c.png)
Здравствуйте! Добавляем описание к пр и ридми.

2021-05-15 09:24 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +RUN cd /reddit && rm Gemfile.lock && bundle install
Можно попробовать поставить ruby-bundler отдельно, не при помощи gem

2021-05-17 05:31 UTC, mzabolotnov commented
Поднят instance в yс. На нем установлен docker. Развернут контейнер с приложением из папки docker-monolith, на образе 16.04. Приложение стартует и работает.

2021-05-19 08:06 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-05-19 18:16 UTC, merged